src/KGC/DashboardBundle/Form/TpeType.php
<?php

// src/KGC/DashboardBundle/Form/TpeType.php


namespace KGC\DashboardBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

/**
 * Class Tpe Type.
 *
 * @category Form
 */
class TpeType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('libelle', 'text', array(
                'required' => true,
            ))
            ->add('enabled', 'checkbox', [
                'required' => false,
                'switch_style' => 5,
            ])
            ->add('hasTelecollecte', 'checkbox', [
                'required' => false,
                'switch_style' => 5,
            ]);
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'KGC\RdvBundle\Entity\TPE',
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'tpe';
    }
}

src/KGC/DashboardBundle/Controller/DashboardController.php
<?php
// src/KGC/DashboardBundle/Controller/DashboardController.php

namespace KGC\DashboardBundle\Controller;

use KGC\RdvBundle\Controller\ConsultationController;
use KGC\RdvBundle\Elastic\Paginator\ElasticPaginator;
use KGC\RdvBundle\Entity\RDV;
use KGC\RdvBundle\Form\RDVAjouterType;
use KGC\UserBundle\Controller\ElasticController;
use KGC\UserBundle\Elastic\Model\ProspectSearch;
use KGC\UserBundle\Form\ProspectEditType;
use KGC\UserBundle\Form\ProspectType;
use KGC\UserBundle\Handler\ProspectEditHandler;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use JMS\SecurityExtraBundle\Annotation\Secure;
use Symfony\Component\HttpFoundation\Request;

/**
 * DashboardController.
 *
 * @category Controller
 *
 * @author Laurene Dourdin <2aurene@gmail.com>
 */
class DashboardController extends Controller
{
    /**
     * Méthode index. Page d'accueil de l'application.
     *
     *
     * @param type $varname Description
     *
     * @return \Symfony\Component\HttpFoundation\Response represents an HTTP response
     */
    public function indexAction(Request $request)
    {
        $role = $this->getUser()->getMainprofil()->getRoleKey();
        if ($role === 'admin') {
            if ('chat' === $this->get('session')->get('dashboard')) {
                $role = 'chat';
            } else {
                $role = 'standard';
            }
        } elseif ($role === 'manager_standar' || $role === 'std_dri_j1') {
            $role = 'simple_standard';
        } elseif (in_array($role, ['admin_phone'])) {
            $role = 'standard';
        } elseif (in_array($role, ['admin_chat', 'manager_chat'])) {
            $this->get('session')->set('dashboard', 'chat');
            $role = 'chat';
        } elseif ($role === 'dri') {
            return $this->redirect($this->get('router')->generate('kgc_dri_page'));
        } elseif ($role === 'j_1') {
            return $this->redirect($this->get('router')->generate('kgc_service_j1'));
        } elseif ($role === 'manager_phone' || $role === "standard" || $role === 'unpaid_service') {
            $role = 'standard';
        } elseif ($role === 'manager_phonist') {
            $role = 'manager_phoniste';
        }  elseif ($role === 'validation') {
            return $this->redirect($this->get('router')->generate('kgc_service_validation'));
        } elseif ($role === 'voyant') {
            return $this->indexVoyant();
        } elseif ($role === 'qualite') {
            return $this->redirect($this->get('router')->generate('kgc_qualite_page'));
        } elseif ($role === 'affiliate') {
            return $this->redirect($this->get('router')->generate('kgc_admin_specific'));
        }

        return $this->render('KGCDashboardBundle:Dashboard:' . $role . '.html.twig');
    }

    /**
     * Méthode step1. Recherche par prospect.
     *
     * @return \Symfony\Component\HttpFoundation\Response represents an HTTP response
     * @Secure(roles="ROLE_PHONISTE, ROLE_MANAGER_PHONIST")
     */
    public function step1Action(Request $request)
    {
        $controler = new ElasticController();
        $controler->setContainer($this->container);
        return $controler->searchProspectAction('phonist', $request);
    }


    /**
     * Méthode step2. Fiche client.
     * @param Request $request
     * @param int $id
     *
     * @return \Symfony\Component\HttpFoundation\Response represents an HTTP response
     * @Secure(roles="ROLE_PHONISTE, ROLE_MANAGER_PHONIST")
     */
    public function step2Action(Request $request, $id)
    {
        $forceEmpty = $request->query->get('forceEmpty');
        $forceEmpty = $forceEmpty ?: false;

        $prospect = $this->getDoctrine()->getManager()->getRepository('KGCSharedBundle:LandingUser')->find($id);
        $em = $this->getDoctrine()->getManager();
        $website = null;
        if ($prospect) {
            $request = $this->get('request');
            $request->getSession()->set('original_prospect', clone $prospect);
            $form_edit = $this->createForm(new ProspectEditType($prospect));
            $form_edithandler = new ProspectEditHandler($form_edit, $request);
            $param_edit = $form_edithandler->process();
            $website = $prospect->getWebsite() ?: $this->getDoctrine()->getManager()->getRepository('KGCSharedBundle:Website')->getWebsiteByAssociationName($prospect->getMyastroWebsite(), false);
            $source = $prospect->getSourceConsult() ?: $this->getDoctrine()->getManager()->getRepository('KGCRdvBundle:Source')->getSourceByAssociationName($prospect->getMyastroSource());
            $codePromo = $prospect->getCodePromo() ?: $this->getDoctrine()->getManager()->getRepository('KGCRdvBundle:CodePromo')->findOneByCode(strtoupper($prospect->getMyastroPromoCode()));
            $voyant = $prospect->getVoyant() ?: $this->getDoctrine()->getManager()->getRepository('KGCUserBundle:Voyant')->findOneByNom($prospect->getMyastroPsychic());
            if (!$prospect->getFormurl()) {
                $find = ['label' => strtolower($prospect->getMyastroUrl())];
                if (!empty($website)) {
                    $find['website'] = $website;
                }
                if (!empty($source)) {
                    $find['source'] = $source;
                }
                $formurl = $this->getDoctrine()->getManager()->getRepository('KGCRdvBundle:FormUrl')->findOneBy($find);
            } else {
                $formurl = $prospect->getFormurl();
            }
            $support = $prospect->getSupport() ?: $this->getDoctrine()->getManager()->getRepository('KGCRdvBundle:Support')->findOneByLibelle($prospect->getMyastroSupport());
            $linkEntities = ['website' => $website, 'source' => $source, 'codePromo' => $codePromo, 'formurl' => $formurl, 'voyant' => $voyant, 'state' => $prospect->getState(), 'support' => $support];
            $formType = new ProspectType($this->getUser(), $param_edit, $em, $linkEntities);
            $form = $this->createForm($formType, $prospect);
            $formhandler = $this->get('kgc.prospect.formhandler');
            $result = $formhandler->process($form, $request);
            if ($result !== null) { // submit
                return $this->redirect($this->generateUrl('kgc_dashboard_phoning22', array('id' => $prospect->getId())));
            } else {
                return $this->render('KGCDashboardBundle:Dashboard:phoniste2.html.twig', array(
                    'prospect' => $prospect,
                    'form' => isset($form) ? $form->createView() : null,
                    'form_edit' => (isset($form_edit)) ? $form_edit->createView() : null,
                    'linkEntities' => $linkEntities,
                    'close' => isset($close) ? $close : null,
                    'options' => ['rdv_btn' => false, 'btn_save' => true, 'fermeture' => true],
                    'forceEmpty' => $forceEmpty,
                    'consultation' => false
                ));
            }
        }
    }


    /**
     * Méthode step22
     *
     * @param int $id
     *
     * @return \Symfony\Component\HttpFoundation\Response represents an HTTP response
     * @Secure(roles="ROLE_PHONISTE, ROLE_MANAGER_PHONIST")
     */
    public function step22Action($id)
    {
        $vue = 'widget';
        $prospect = $this->getDoctrine()->getRepository('KGCSharedBundle:LandingUser')->find($id);
        $currUser = $this->getUser();
        $em = $this->getDoctrine()->getManager();
        $rdv = new RDV($currUser);
        $toComplete = [];
        if ($prospect) {
            $website = $this->getDoctrine()->getRepository('KGCSharedBundle:Website')->getWebsiteByAssociationName($prospect->getMyastroWebsite(), false);
            if ($website) {
                $rdv->setWebsite($website);
            }
            $source = $this->getDoctrine()->getRepository('KGCRdvBundle:Source')->getSourceByAssociationName($prospect->getMyastroSource());
            if ($source) {
                $rdv->setSource($source);
            }
            $voyant = $this->getDoctrine()->getRepository('KGCUserBundle:Voyant')->findOneByNom($prospect->getMyastroPsychic());
            if ($voyant) {
                $rdv->setVoyant($voyant);
            }
            $codePromo = $this->getDoctrine()->getRepository('KGCRdvBundle:CodePromo')->findOneByCode(strtoupper($prospect->getMyastroPromoCode()));
            if ($codePromo) {
                $rdv->setCodePromo($codePromo);
            }
            $find = ['label' => strtolower($prospect->getMyastroUrl())];
            if (!empty($website)) {
                $find['website'] = $website;
            }
            if (!empty($source)) {
                $find['source'] = $source;
            }
            $formurl = $this->getDoctrine()->getRepository('KGCRdvBundle:FormUrl')->findOneBy($find);
            if ($formurl) {
                $rdv->setFormUrl($formurl);
            }
            $toComplete['idAstro_valeur'] = $prospect->getMyastroId();
            $toComplete['gclid'] = $prospect->getMyastroGclid();
            $toComplete['numtel1'] = $prospect->getPhone();
            $toComplete['questionSubject'] = $prospect->getQuestionSubject();
            $toComplete['questionContent'] = $prospect->getQuestionContent();
            $toComplete['questionText'] = $prospect->getQuestionText();
            $toComplete['spouseName'] = $prospect->getSpouseName();
            $toComplete['spouseBirthday'] = $prospect->getSpouseBirthday() ? $prospect->getSpouseBirthday()->format('d/m/Y') : '';
            $toComplete['spouseSign'] = $prospect->getSpouseSign();
            $toComplete['adresse_pays'] = $prospect->getCountry();
            $client = ($prospect->getClient()) ?: $this->getDoctrine()->getRepository('KGCSharedBundle:LandingUser')->getProspectClient($prospect);
            if ($client) {
                $rdv->setClient($client);
                $toComplete['client_prenom'] = $prospect->getFirstName();

src/KGC/DashboardBundle/Resources/views/Dashboard/chat.html.twig
{# src/KGC/DashboardBundle/Ressources/views/Dashboard/standard.html.twig #}

{% extends "KGCDashboardBundle::layout.html.twig" %}

{% block ariane %}
    {% set fil = ['Tableau de bord'] %}
    {{ parent() }}
{% endblock %}

{% block page_header %}
    {% set reload = {
    'url':'#rdv_planning_chat, #rdv_status_done,#rdv_status_refused, #rdv_stats_general, #rdv_stats_chatter, #rdv_stats_users'
    } %}
    {{ parent()}}
{% endblock %}

{% block dashboard_body %}
    <div class="row" style="min-height: 200px;">
        <div class="col-lg-4">
            <form method="post" action="{{ path('kgc_chat_planning_widget') }}" class="ajax_load" id="rdv_planning_chat"></form>
        </div>
        <div class="col-lg-4">
            <form method="post" action="{{ path('kgc_chat_last_status', {'status': constant('KGC\\ChatBundle\\Entity\\ChatRoom::STATUS_CLOSED')}) }}" class="ajax_load" id="rdv_status_done"></form>
            <div class="space-6"></div>
            <form method="post" action="{{ path('kgc_chat_last_status', {'status': constant('KGC\\ChatBundle\\Entity\\ChatRoom::STATUS_REFUSED')}) }}" class="ajax_load" id="rdv_status_refused"></form>
        </div>
        <div class="col-lg-4">
            <form method="post" action="{{ path('kgc_chat_stats_users') }}" class="ajax_load" id="rdv_stats_users"></form>
            <div class="space-6"></div>
            {% if is_granted('ROLE_ADMIN_CHAT') %}
                <form method="post" action="{{ path('kgc_chat_stats_general') }}" class="ajax_load" id="rdv_stats_general"></form>
                <div class="space-6"></div>
            {% endif %}
            <form method="post" action="{{ path('kgc_chat_stats_chatter') }}" class="ajax_load" id="rdv_stats_chatter"></form>
        </div>
    </div>
{% endblock %}

src/KGC/DashboardBundle/Resources/views/Dashboard/flashbags.html.twig
{# src/KGC/DashboardBundle/Ressources/views/Dashboard/flashbags.html.twig #}

<div class="hidden">
    {% for flash in flashbag %}
    <p class="gritter" data-title="{{ flash.titre }}" data-class="gritter-{{ flash.class }}" data-image="{{ app.request.getSchemeAndHttpHost() ~ asset(img_path ~ flash.img ~ '.png') }}">
        {{ flash.msg }}
    </p>
    {% endfor %}
    {% if modal is not null %}
        <a class="modal-auto-load" href="{{ modal[0] }}"></a>
    {% endif %}
</div>

src/KGC/DashboardBundle/Resources/views/Dashboard/in-construction.html.twig
{% extends "KGCDashboardBundle::layout.html.twig" %}

{% block ariane %}
    {% set fil = ['Administration'] %}
    {{ parent() }}
{% endblock %}


{% block page_header %}
    <div class="page-header">
        <div class="pull-right">
            <a class="ajax_reload close" href="" title="Recharger">
                <i class="icon-refresh"></i>
            </a>
        </div>
    </div>
{% endblock %}

{% block dashboard_body %}
    <div class="well center text-muted">
        <h1><i class="icon-wrench"></i> En construction</h1>
    </div>
{% endblock %}

src/KGC/DashboardBundle/Resources/views/Dashboard/index.html.twig
{# src/KGC/DashboardBundle/Ressources/views/Dashboard/index.html.twig #}

{% extends "KGCDashboardBundle::layout.html.twig" %}

{% block ariane %}
    {% set fil = ['Tableau de bord'] %}
    {{ parent() }}
{% endblock %}

src/KGC/DashboardBundle/Resources/views/Dashboard/menu.html.twig
{# src/KGC/DashboardBundle/Resources/views/Dashboard/menu.html.twig #}

<div class="sidebar-shortcuts sidebar-fixed" id="sidebar-shortcuts">
    <div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
        <button class="btn btn-success">
            <!--<i class="icon-signal"></i>-->
        </button>
        <button class="btn btn-info">
            <!--<i class="icon-pencil"></i>-->
        </button>
        <button class="btn btn-warning">
            <!--<i class="icon-group"></i>-->
        </button>
        <button class="btn btn-danger">
            <!--<i class="icon-cogs"></i>-->
        </button>
    </div>

    <div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
        <span class="btn btn-success"></span>
        <span class="btn btn-info"></span>
        <span class="btn btn-warning"></span>
        <span class="btn btn-danger"></span>
    </div>
</div><!-- #sidebar-shortcuts -->
<ul class="nav nav-list">
    {% for lien in liste_liens %}
        <li class="{{ lien.active ? 'active' }} {{ lien.active and lien.subs is defined ? 'open' }}">
            <a href="{{ path(lien.route) }}" {{ lien.subs is defined ? 'class=dropdown-toggle' }}>
                <i class="icon-{{ lien.icone }}"></i>
                <span class="menu-text">{{ lien.intitule }}
                    {% if (lien.badge is defined) and lien.badge > 0 %}
                        <span class="badge badge-primary" style="margin-right:15px">{{ lien.badge }}</span>
                    {% endif %}
                </span>
                {% if lien.subs is defined %}
                    <b class="arrow icon-angle-down"></b>
                {% endif %}
            </a>
            {% if lien.subs is defined %}
                <ul class="submenu">
                    {% for sub in lien.subs %}
                        <li class="{{ sub.active ? 'active' : '' }}">
                            <a href="{{ path(sub.route) }}">
                                <i class="icon-double-angle-right"></i>
                                {{ sub.intitule }}
                            </a>
                            <b class="arrow"></b>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </li>
    {% endfor %}
</ul>

<div class="sidebar-collapse" id="sidebar-collapse">
    <i class="icon-double-angle-left" data-icon1="icon-double-angle-left" data-icon2="icon-double-angle-right"></i>
</div>

<script type="text/javascript">
    // récupération du paramètre enregistré
    try {
        ace.settings.check('sidebar', 'collapsed')
    } catch (e) {
    }
</script>

src/KGC/DashboardBundle/Resources/views/Dashboard/phoniste-etape1.html.twig
{# src/KGC/DashboardBundle/Ressources/views/Dashboard/phoniste-etape1.html.twig #}

{% extends "KGCDashboardBundle::layout.html.twig" %}

{% block ariane %}
    {% set fil = ['Tableau de bord'] %}
    {{ parent() }}
{% endblock %}

{% block page_header %}
    {% set reload = { 'url':'#rdv-add, #phoniste_legend, #phoniste_objective, #phoniste_bonuses' } %}
    {{ parent() }}
{% endblock %}

{% block dashboard_body %}
    <div class="row">
        <div class="col-lg-8">
            <div class="widget-box">
                <div class="widget-header">
                    <h5>
                        <a href="#" data-action="collapse">
                            <i class="icon-chevron-up"></i>
                            Rechercher un prospect<b></b>
                        </a>
                    </h5>
                </div>
                <div class="widget-body search-advanced elastic_search">
                    <div class="widget-main">
                        <div class="widget-box ">
                            <div class="widget-header header-color-blue2">
                                <h5>
                                    <b> {{ paginator.totalItemsCount }} résultats</b>

                                </h5>
                                <div class="widget-toolbar no-border">
                                </div>
                            </div>
                            <div class="widget-body  search-advanced">
                                <div class="widget-main no-padding ">
                                    <form method="post" action="{{ path('kgc_dashboard_phoning1') }}">
                                        <div class="row">
                                            <div class="col-lg-6 col-md-6">
                                                {{ form_row(form.idastro) }}
                                            </div>
                                            <div class="col-lg-6 col-md-6">
                                                {{ form_row(form.dateBegin) }}
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-6 col-md-6">
                                                {{ form_row(form.name) }}
                                            </div>
                                            <div class="col-lg-6 col-md-6">
                                                {{ form_row(form.birthdate) }}
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-6 col-md-6">
                                                {{ form_row(form.mail) }}
                                            </div>
                                            <div class="col-lg-6 col-md-6">
                                                {{ form_row(form.phones) }}
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-6 col-md-6">
                                                <button type="submit" class="save btn btn-success btn-block">Rechercher</button>
                                            </div>
                                            <div class="col-lg-6 col-md-6">
                                                <button type="button" class="btn btn-info btn-block js-reset-empty">Effacer le formulaire</button>
                                                <div style="display:none;">{{ form_rest(form) }}</div>
                                            </div>
                                        </div>
                                    </form>
                                    <div class="space-6"></div>
                                    {% if paginator %}
                                        {% set fiches = paginator.elements %}
                                        {% if fiches|length > 0 %}
                                            <table class="table table-striped table-hover valign-middle" id="table-0">
                                                <thead>
                                                    <tr>
                                                        <th class="center">ID astro</th>
                                                        <th class="center">Date d'inscription</th>
                                                        <th class="center">Prénom</th>
                                                        <th class="center">Date de naissance</th>
                                                        <th class="center">Email</th>
                                                        <th class="center">Site</th>
                                                        <th class="center">Source</th>
                                                        <th class="center">URL</th>
                                                        <th></th>
                                                    <tr>
                                                </thead>
                                                <tbody>
                                                    {% for prospect in fiches %}
                                                        <tr>
                                                            <td class="center">{{ prospect.myastroId }}</td>
                                                            <td class="center">{{ prospect.createdAt|date("d/m/Y") }}</td>
                                                            <td class="center">{{ prospect.firstname }}</td>
                                                            <td class="center">{{ prospect.birthday|date("d/m/Y") }}</td>
                                                            <td class="center">{{ prospect.email }}</td>
                                                            <td class="center">{{ prospect.myastroWebsite }}</td>
                                                            <td class="center">{{ prospect.myastroSource }}</td>
                                                            <td class="center">{{ prospect.myastroUrl }}</td>
                                                            <td class="center">
                                                                <a href="{{ path('kgc_dashboard_phoning2',{'id':prospect.id}) }}" class="btn btn-xs btn-grey tooltip-grey" role="button" title="" data-rel="tooltip" data-placement="right" data-original-title="voir la fiche prospect">
                                                                    <i class="icon-file"></i>
                                                                </a>
                                                            </td>
                                                        </tr>
                                                    {% else %}
                                                        <tr>
                                                            <td colspan="4">Aucun résultat</td>
                                                        </tr>
                                                    {% endfor %}
                                                </tbody>
                                            </table>
                                            <div class="space-6"></div>
                                            {% if paginator.totalPagesCount %}
                                                <div class="row align-center">
                                                    <div class="col-lg-12">
                                                        <strong>{{ paginator.totalItemsCount }}</strong> résultats.
                                                        Page <strong>{{ paginator.currentPage }}</strong> sur <strong>{{ paginator.totalPagesCount }}</strong>.
                                                        <br/>
                                                        {% if paginator.totalPagesCount > 1 %}
                                                            <ul class="pagination no-margin">
                                                                <li><a href="#" class="js-page-target" data-page-target="1">&lt;&lt;</a></li>
                                                                <li><a href="javascript:void(0);">...</a></li>
                                                                {% for page in paginator.showPages %}
                                                                    <li class="{{ page == paginator.currentPage ? 'active' : '' }}">
                                                                        <a href="#" class="js-page-target" data-page-target="{{ page }}">{{ page }}</a>
                                                                    </li>
                                                                {% endfor %}
                                                                <li><a href="javascript:void(0);">...</a></li>
                                                                <li><a href="#" class="js-page-target" data-page-target="{{ paginator.totalPagesCount }}">&gt;&gt;</a></li>
                                                            </ul>
                                                        {% endif %}
                                                    </div>
                                                </div>
                                                <div class="space-6"></div>
                                            {% endif %}
                                        {% endif %}
                                    {% endif %}
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12">
                                            <div class="pull-right">
                                                <a class="btn btn-block btn-primary" href="{{ path('kgc_dashboard_phoning3') }}" role="button" title="APPEL ENTRANT NON PROSPECT">
                                                    APPEL ENTRANT NON PROSPECT
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <form method="post" action="{{ path('kgc_stat_phoniste_objective') }}" class="ajax_load form-horizontal" id="phoniste_objective"></form>
            <div class="space-6"></div>
            <form method="post" action="{{ path('kgc_stat_phoniste_bonuses') }}" class="ajax_load form-horizontal" id="phoniste_bonuses"></form>
            <div class="space-6"></div>
            <form method="post" action="{{ path('kgc_stat_phoniste_legend') }}" class="ajax_load form-horizontal" id="phoniste_legend"></form>
        </div>
    </div>
{% endblock %}

src/KGC/DashboardBundle/Resources/views/Dashboard/phoniste.html.twig
{# src/KGC/DashboardBundle/Ressources/views/Dashboard/phoniste.html.twig #}

{% extends "KGCDashboardBundle::layout.html.twig" %}

{% block ariane %}
    {% set fil = ['Tableau de bord'] %}
    {{ parent() }}
{% endblock %}

{% block page_header %}
    {% set reload = { 'url':'#rdv-add, #phoniste_legend, #phoniste_objective, #phoniste_bonuses' } %}
    {{ parent()}}
{% endblock %}

{% block dashboard_body %}
    <div class="row">
        <div class="col-lg-8">
            <form method="post" action="{{ path('kgc_rdv_add') }}" class="ajax_load form-horizontal" data-refresh="#phoniste_objective,#phoniste_bonuses" id="rdv-add"></form>
        </div>
        <div class="col-lg-4">
            <form method="post" action="{{ path('kgc_stat_phoniste_circle_objectives') }}" class="ajax_load form-horizontal" id="phoniste_objective"></form>
            <div class="space-6"></div>
            <form method="post" action="{{ path('kgc_stat_phoniste_bonuses_recap') }}" class="ajax_load form-horizontal" id="phoniste_bonuses"></form>
        </div>
    </div>
{% endblock %}

src/KGC/DashboardBundle/Resources/views/Dashboard/phoniste3.html.twig
{# src/KGC/DashboardBundle/Ressources/views/Dashboard/phoniste.html.twig #}

{% extends "KGCDashboardBundle::layout.html.twig" %}

{% block ariane %}
    {% set fil = ['Tableau de bord'] %}
    {{ parent() }}
{% endblock %}

{% block page_header %}
    {% set reload = { 'url':'#rdv-add, #phoniste_legend, #phoniste_objective, #phoniste_bonuses' } %}
    {{ parent() }}
{% endblock %}

{% block dashboard_body %}
    <div class="row">
        <div class="col-lg-8">
            {% if toComplete is defined and toComplete is not empty %}
            <form method="post" action="{{ path('kgc_rdv_add_by_prospect',{'vue':'widget','id':prospect.id}) }}" class="ajax_load form-horizontal" data-refresh="#phoniste_objective,#phoniste_bonuses" id="rdv-add"></form>
            {% else %}
                <form method="post" action="{{ path('kgc_rdv_add') }}" class="ajax_load form-horizontal" data-refresh="#phoniste_objective,#phoniste_bonuses" id="rdv-add"></form>
            {% endif %}
        </div>
        <div class="col-lg-4">
            <form method="post" action="{{ path('kgc_stat_phoniste_objective') }}" class="ajax_load form-horizontal" id="phoniste_objective"></form>
            <div class="space-6"></div>
            <form method="post" action="{{ path('kgc_stat_phoniste_bonuses') }}" class="ajax_load form-horizontal" id="phoniste_bonuses"></form>
            <div class="space-6"></div>
            <form method="post" action="{{ path('kgc_stat_phoniste_legend') }}" class="ajax_load form-horizontal" id="phoniste_legend"></form>
        </div>
    </div>
{% endblock %}