src/KGC/ChatBundle/Entity/ChatParticipant.php
<?php

namespace KGC\ChatBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @category Entity
 *
 * @ORM\Table(name="chat_participant")
 * @ORM\Entity(repositoryClass="KGC\ChatBundle\Repository\ChatParticipantRepository")
 */
class ChatParticipant implements \KGC\Bundle\SharedBundle\Entity\Interfaces\ChatParticipant
{
    const LEAVE_REASON_HEARTBEAT = 'heartbeat';

    /**
     * @var int
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var \DateTime
     * @ORM\Column(name="join_date", type="datetime")
     */
    protected $joinDate;

    /**
     * @var \DateTime
     * @ORM\Column(name="leave_date", type="datetime", nullable=true)
     */
    protected $leaveDate;

    /**
     * @var string
     * @ORM\Column(name="leave_reason", type="string", length=25, nullable=true)
     */
    protected $leaveReason;

    /**
     * @ORM\ManyToOne(targetEntity="\KGC\UserBundle\Entity\Utilisateur", inversedBy="chatParticipants")
     * @ORM\JoinColumn(name="psychic_id", referencedColumnName="uti_id")
     */
    protected $psychic;

    /**
     * @ORM\ManyToOne(targetEntity="\KGC\UserBundle\Entity\Voyant")
     * @ORM\JoinColumn(name="virtual_psychic_id", referencedColumnName="voy_id", nullable=false)
     */
    protected $virtualPsychic;

    /**
     * @ORM\ManyToOne(targetEntity="\KGC\Bundle\SharedBundle\Entity\Client", inversedBy="chatParticipants")
     * @ORM\JoinColumn(name="client_id", referencedColumnName="id")
     */
    protected $client;

    /**
     * @ORM\ManyToOne(targetEntity="\KGC\ChatBundle\Entity\ChatRoom", inversedBy="chatParticipants")
     * @ORM\JoinColumn(name="chat_room_id", referencedColumnName="id", nullable=false)
     */
    protected $chatRoom;

    /**
     * Constructeur.
     */
    public function __construct()
    {
        $this->joinDate = new \DateTime();
    }

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set join date.
     *
     * @param \DateTime $joinDate
     *
     * @return \KGC\ChatBundle\Entity\ChatParticipant
     */
    public function setJoinDate(\DateTime $joinDate)
    {
        $this->joinDate = $joinDate;

        return $this;
    }

    /**
     * Get join date.
     *
     * @return \DateTime
     */
    public function getJoinDate()
    {
        return $this->joinDate;
    }

    /**
     * Set leave date.
     *
     * @param \DateTime $leaveDate
     *
     * @return \KGC\ChatBundle\Entity\ChatParticipant
     */
    public function setLeaveDate(\DateTime $leaveDate = null)
    {
        $this->leaveDate = $leaveDate;

        return $this;
    }

    /**
     * Get leave date.
     *
     * @return \DateTime
     */
    public function getLeaveDate()
    {
        return $this->leaveDate;
    }

    /**
     * Set leaveReason
     *
     * @param string $leaveReason
     *
     * @return ChatParticipant
     */
    public function setLeaveReason($leaveReason = null)
    {
        $this->leaveReason = $leaveReason;

        return $this;
    }

    /**
     * Get leaveReason
     *
     * @return string
     */
    public function getLeaveReason()
    {
        return $this->leaveReason;
    }

    /**
     * Get leave reasons list
     *
     * @return array
     */
    public static function getLeaveReasonsList()
    {
        return [
            self::LEAVE_REASON_HEARTBEAT
        ];
    }

    /**
     * Set client.
     *
     * @param \KGC\ClientBundle\Entity\Client $client
     *
     * @return \KGC\ChatBundle\Entity\ChatParticipant
     */
    public function setClient($client)
    {
        $this->client = $client;

        return $this;
    }

    /**
     * Get client.
     *
     * @return \KGC\ClientBundle\Entity\Client
     */
    public function getClient()
    {
        return $this->client;
    }

    /**
     * Set psychic.
     *
     * @param \KGC\UserBundle\Entity\Utilisateur $psychic
     *
     * @return \KGC\ChatBundle\Entity\ChatParticipant
     */
    public function setPsychic($psychic)
    {
        $this->psychic = $psychic;

        return $this;
    }

    /**
     * Get psychic.
     *
     * @return \KGC\UserBundle\Entity\Utilisateur
     */
    public function getPsychic()
    {
        return $this->psychic;
    }

    /**
     * Set virtualPsychic.
     *
     * @param \KGC\UserBundle\Entity\Voyant $virtualPsychic
     *
     * @return \KGC\ChatBundle\Entity\ChatParticipant
     */
    public function setVirtualPsychic($virtualPsychic)
    {
        $this->virtualPsychic = $virtualPsychic;

        return $this;
    }

    /**
     * Get virtualPsychic.
     *
     * @return \KGC\UserBundle\Entity\Voyant
     */
    public function getVirtualPsychic()
    {
        return $this->virtualPsychic;
    }

    /**
     * Set chat room.
     *
     * @param \KGC\ChatBundle\Entity\ChatRoom $chatRoom
     *
     * @return \KGC\ChatBundle\Entity\ChatParticipant
     */
    public function setChatRoom($chatRoom)
    {
        $this->chatRoom = $chatRoom;

        return $this;
    }

    /**
     * Get chat room.
     *
     * @return \KGC\ChatBundle\Entity\ChatRoom
     */
    public function getChatRoom()
    {
        return $this->chatRoom;
    }

    /**
     * Utility method to directly get the user related.
     *
     * @return Utilisateur, Client or null if no one is set
     */
    public function getUser()
    {
        return $this->psychic !== null ? $this->psychic : $this->client;
    }

    public function isPsychic()
    {
        return $this->psychic !== null;
    }

    public function getParticipantName()
    {
        return $this->psychic !== null ? $this->virtualPsychic->getNom() : $this->client->getPrenom();
    }

    public function getPhysicalPsychicName()
    {
        return $this->psychic !== null ? $this->psychic->getUsername() : null;
    }

    public function getVirtualPsychicName()
    {
        return $this->psychic !== null ? $this->virtualPsychic->getNom() : null;
    }
}

src/KGC/ChatBundle/Entity/ChatRoom.php
<?php

namespace KGC\ChatBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use KGC\Bundle\SharedBundle\Entity\Website;

/**
 * @category Entity
 *
 * @ORM\Table(name="chat_room")
 * @ORM\Entity(repositoryClass="KGC\ChatBundle\Repository\ChatRoomRepository")
 */
class ChatRoom implements \KGC\Bundle\SharedBundle\Entity\Interfaces\ChatRoom
{
    /**
     * Constants on room's status.
     */
    const STATUS_NOT_STARTED = 0;
    const STATUS_ON_GOING = 1;
    const STATUS_CLOSED = 2;
    const STATUS_REFUSED = 3;

    /**
     * @var int
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     * @ORM\Column(name="entitled", type="string")
     */
    protected $entitled;

    /**
     * @var int
     * @ORM\Column(name="status", type="smallint")
     */
    protected $status;

    /**
     * @var \DateTime
     * @ORM\Column(name="date_created", type="datetime")
     */
    protected $dateCreated;

    /**
     * @var \DateTime
     * @ORM\Column(name="start_date", type="datetime", nullable=true)
     */
    protected $startDate;

    /**
     * @var \DateTime
     * @ORM\Column(name="end_date", type="datetime", nullable=true)
     */
    protected $endDate;

    /**
     * @var ArrayCollection
     * @ORM\OneToMany(targetEntity="\KGC\ChatBundle\Entity\ChatMessage", mappedBy="chatRoom")
     */
    protected $chatMessages;

    /**
     * @var ArrayCollection
     * @ORM\OneToMany(targetEntity="\KGC\ChatBundle\Entity\ChatParticipant", mappedBy="chatRoom")
     */
    protected $chatParticipants;

    /**
     * @var ArrayCollection
     * @ORM\OneToMany(targetEntity="\KGC\ChatBundle\Entity\ChatRoomFormulaRate", mappedBy="chatRoom")
     */
    protected $chatRoomFormulaRates;

    /**
     * @ORM\ManyToOne(targetEntity="\KGC\Bundle\SharedBundle\Entity\Website", inversedBy="chatRooms")
     * @ORM\JoinColumn(name="website_id", referencedColumnName="web_id", nullable=false)
     */
    protected $website;

    /**
     * @ORM\ManyToOne(targetEntity="\KGC\ChatBundle\Entity\ChatType")
     * @ORM\JoinColumn(name="chat_type_id", referencedColumnName="id", nullable=false)
     */
    protected $chatType;

    /**
     * @var Source
     *
     * @ORM\ManyToOne(targetEntity="\KGC\Bundle\SharedBundle\Entity\Source", cascade={"persist"})
     * @ORM\JoinColumn(nullable=true, name="source", referencedColumnName="id")
     */
    protected $source;

    /**
     * Constructeur.
     */
    public function __construct()
    {
        $this->dateCreated = new \DateTime();
        $this->chatMessages = new ArrayCollection();
        $this->chatParticipants = new ArrayCollection();
        $this->chatRoomFormulaRates = new ArrayCollection();

        $this->status = self::STATUS_NOT_STARTED;
    }

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set entitled.
     *
     * @param string $entitled
     *
     * @return \KGC\ChatBundle\Entity\ChatRoom
     */
    public function setEntitled($entitled)
    {
        $this->entitled = $entitled;

        return $this;
    }

    /**
     * Get entitled.
     *
     * @return string
     */
    public function getEntitled()
    {
        return $this->entitled;
    }

    /**
     * Set status.
     *
     * @param int $status
     *
     * @return \KGC\ChatBundle\Entity\ChatRoom
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status.
     *
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function isNotStarted()
    {
        return $this->status === self::STATUS_NOT_STARTED;
    }

    public function isOnGoing()
    {
        return $this->status === self::STATUS_ON_GOING;
    }

    public function isClosed()
    {
        return $this->status === self::STATUS_CLOSED;
    }

    public function isRefused()
    {
        return $this->status === self::STATUS_REFUSED;
    }

    /**
     * Set date created.
     *
     * @param \DateTime $dateCreated
     *
     * @return \KGC\ChatBundle\Entity\ChatRoom
     */
    public function setDateCreated(\DateTime $dateCreated)
    {
        $this->dateCreated = $dateCreated;

        return $this;
    }

    /**
     * Get date created.
     *
     * @return \DateTime
     */
    public function getDateCreated()
    {
        return $this->dateCreated;
    }

    /**
     * Set start date.
     *
     * @param \DateTime $startDate
     *
     * @return \KGC\ChatBundle\Entity\ChatRoom
     */
    public function setStartDate(\DateTime $startDate)
    {
        $this->startDate = $startDate;

        return $this;
    }

    /**
     * Get start date.
     *
     * @return \DateTime
     */
    public function getStartDate()
    {
        return $this->startDate;
    }

    /**
     * Set end date.
     *
     * @param \DateTime $endDate
     *
     * @return \KGC\ChatBundle\Entity\ChatRoom
     */
    public function setEndDate(\DateTime $endDate)
    {
        $this->endDate = $endDate;

        return $this;
    }

    /**
     * Get end date.
     *
     * @return \DateTime
     */
    public function getEndDate()
    {
        return $this->endDate;
    }

    /**
     * Return this object convert to array, ready to be converted to json.
     *
     * @return array
     */
    public function toJsonArray()
    {
        return array(
            'id' => $this->getId(),
            'entitled' => $this->getEntitled(),
            'status' => $this->getStatus(),
            'date_created' => $this->getDateCreated()->getTimestamp(),
            'start_date' => ($this->getStartDate() ? $this->getStartDate()->getTimestamp() : null),
            'end_date' => ($this->getEndDate() ? $this->getEndDate()->getTimestamp() : null),
        );
    }

    /**
     * Set chatMessages.
     *
     * @param ArrayCollection
     *
     * @return \KGC\ChatBundle\Entity\ChatRoom
     */
    public function setChatMessages($chatMessages)
    {
        $this->chatMessages = $chatMessages;

        return $this;
    }

    /**
     * Get chatMessages.
     *
     * @return ArrayCollection
     */
    public function getChatMessages()
    {
        return $this->chatMessages;
    }

    /**
     * Add chatMessage.
     *
     * @return \KGC\ChatBundle\Entity\ChatRoom
     */
    public function addChatMessage(ChatMessage $chatMessage)
    {
        $this->chatMessages[] = $chatMessage;

        return $this;
    }

    /**
     * Remove chatMessage.
     *
     * @return \KGC\ChatBundle\Entity\ChatRoom
     */
    public function removeChatMessage(ChatMessage $chatMessage)
    {
        $this->chatMessages->removeElement($chatMessage);

        return $this;
    }

    /**
     * Set chatParticipants.
     *
     * @param ArrayCollection
     *
     * @return \KGC\ChatBundle\Entity\ChatRoom
     */
    public function setChatParticipants($chatParticipants)
    {
        $this->chatParticipants = $chatParticipants;

        return $this;
    }

    /**
     * Get chatParticipants.
     *
     * @return ArrayCollection
     */
    public function getChatParticipants()
    {
        return $this->chatParticipants;
    }

    /**
     * Add chatParticipant.
     *
     * @return \KGC\ChatBundle\Entity\ChatRoom
     */
    public function addChatParticipant(ChatParticipant $chatParticipant)
    {
        $this->chatParticipants[] = $chatParticipant;

        return $this;
    }

    /**
     * Remove chatParticipant.
     *
     * @return \KGC\ChatBundle\Entity\ChatRoom
     */
    public function removeChatParticipant(ChatParticipant $chatParticipant)
    {
        $this->chatParticipants->removeElement($chatParticipant);

        return $this;
    }

    /**
     * Set chatRoomFormulaRates.
     *
     * @param ArrayCollection
     *
     * @return \KGC\ChatBundle\Entity\ChatRoom
     */
    public function setChatRoomFormulaRates($chatRoomFormulaRates)
    {
        $this->chatRoomFormulaRates = $chatRoomFormulaRates;

        return $this;
    }

    /**
     * Get chatRoomFormulaRates.
     *
     * @return ArrayCollection
     */
    public function getChatRoomFormulaRates()
    {
        return $this->chatRoomFormulaRates;
    }

    /**
     * Add chatRoomFormulaRate.
     *
     * @return \KGC\ChatBundle\Entity\ChatRoom
     */
    public function addChatRoomFormulaRate(ChatRoomFormulaRate $chatRoomFormulaRate)
    {
        $this->chatRoomFormulaRates[] = $chatRoomFormulaRate;

        return $this;
    }

    /**
     * Remove chatRoomFormulaRate.
     *
     * @return \KGC\ChatBundle\Entity\ChatRoom
     */
    public function removeChatRoomFormulaRate(ChatRoomFormulaRate $chatRoomFormulaRate)
    {
        $this->chatRoomFormulaRates->removeElement($chatRoomFormulaRate);

        return $this;
    }

    /**
     * Get the client if there is one in this room.
     *
     * @return Client | null
     */
    public function getClient()
    {
        $client = null;
        foreach ($this->getChatParticipants() as $roomChatParticipant) {
            if (($clientChatParticipant = $roomChatParticipant->getClient()) !== null) {
                $client = $clientChatParticipant;
                break;
            }
        }

        return $client;
    }

    /**
     * Get participant related to main room psychic
     *
     * @return ChatParticipant
     */
    public function getPsychicParticipant()
    {
        $result = null;
        foreach ($this->getChatParticipants() as $roomChatParticipant) {
            if ($roomChatParticipant->getPsychic() !== null && ($result === null || $roomChatParticipant->getId() > $result->getId())) {
                $result = $roomChatParticipant;
            }
        }

        return $result;
    }

    /**

src/KGC/ChatBundle/Resources/views/Chat/chat_client.html.twig
{% set prospect = client.getLandingByWebsite(website) %}
{% embed '::widgetlayout.html.twig' %}

    {% set widget_options = {
    'titre' : 'Coordonnées client',
    'header_class' : 'widget-header-small',
    'refresh' : null,
    'collapse' : true,
    'no_padding' : true,
    } %}

    {% block widget_toolbar %}
        <a class="debugdata tooltip-light" data-rel="tooltip" title="" data-placement="right" data-original-title="id : {{ client.id }}">
            <i class="icon-cog"></i>
        </a>
        {% if app.user.isAdmin() or app.user.isManagerChat() %}
            {% if client.numtel1 is defined and client.numtel1 != "" or client.numtel2 is defined and client.numtel2 != "" %}
                <a style="margin-top: 3px;margin-right: 5px;" title="Envoyer un sms" class="modal-load btn btn-xs pull-right" href="{{ path('kgc_chat_prepare_sms',{'id':client.id}) }}">
                    <i class="icon-comments bigger-120"></i> Envoyer un sms
                </a>
            {% endif %}
            <a style="margin-top: 3px;margin-right: 5px;" title=" Envoyer un mail" class="modal-load btn btn-xs pull-right" href="{{ path('kgc_chat_prepare_mail',{'id':client.id}) }}">
                <i class="icon-envelope bigger-120"></i> Envoyer un mail
            </a>
        {% endif %}
    {% endblock %}

    {% block widget_main %}

        <table class="table table-striped ">
            <tbody>
            <tr>
                <th>
                    <span>Prénom</span>
                </th>
                <td>
                    {{ client.prenom }}
                </td>
            </tr>
            <tr>
                <th>
                    <span>Pseudo</span>
                </th>
                <td>
                    {{ client.username }}
                </td>
            </tr>
            <tr>
                <th>
                    <span>Genre</span>
                </th>
                <td>
                    {{ client.genre }}
                </td>
            </tr>
            <tr>
                <th>
                    <span>Adresse mail</span>
                </th>
                <td>
                    {{ client.email }}
                </td>
            </tr>
            {% if client.numtel1 is defined and not client.numtel1 == "" %}
                <tr>
                    <th>
                        <span>Téléphone</span>
                    </th>
                    <td>
                        {{ client.numtel1 }}
                    </td>
                </tr>
            {% elseif client.numtel2 is defined and not client.numtel2 == "" %}
                <tr>
                    <th>
                        <span>Téléphone</span>
                    </th>
                    <td>
                        {{ client.numtel2 }}
                    </td>
                </tr>
            {% endif %}

            <tr>
                <th style="width:160px;">
                    <span>
                       Date de naissance
                        {{ '(' ~ (client.dateNaissance | age) ~ ' ans - ' ~ (client.dateNaissance | astro) ~ ')' }}
                    </span>
                </th>
                <td>
                    {{ client.dateNaissance | date('d/m/Y') }}
                </td>
            </tr>

            </tbody>
        </table>

    {% endblock %}
{% endembed %}

{% embed '::widgetlayout.html.twig' %}

    {% set widget_options = {
    'titre' : 'Informations tchat',
    'header_class' : 'widget-header-small',
    'refresh' : null,
    'collapse' : true,
    'no_padding' : true,
    } %}

    {% block widget_main %}

        <table class="table table-striped ">
            <tbody>
            <tr>
                <th>
                    <span>Sujet principal</span>
                </th>
                <td>
                    {{ client.chatInfoSubject }}
                </td>
            </tr>
            <tr>
                <th>
                    <span>Prénom du conjoint</span>
                </th>
                <td>
                    {{ client.chatInfoPartner }}
                </td>
            </tr>
            <tr>
                <th>
                    <span>Conseil principal</span>
                </th>
                <td>
                    {{ client.chatInfoAdvice }}
                </td>
            </tr>
            </tbody>
        </table>

    {% endblock %}
{% endembed %}


{% if prospect is not null %}
    {% embed '::widgetlayout.html.twig' %}
            {% set widget_options = {
            'titre' : 'UTM',
            'header_class' : 'widget-header-small',
            'refresh' : null,
            'collapse' : true,
            'no_padding' : true,
            } %}

            {% block widget_main %}

                <table class="table table-striped">
                    <tbody>
                        <tr>
                            <th>
                                <span>Site</span>
                            </th>
                            <td>
                                {{ prospect.myastroWebsite }}
                            </td>
                        </tr>
                        <tr>
                            <th>
                                <span>Source</span>
                            </th>
                            <td>
                                {{ prospect.myastroSource }}
                            </td>
                        </tr>
                        <tr>
                            <th>
                                <span>URL</span>
                            </th>
                            <td>
                                {{ prospect.myastroUrl }}
                            </td>
                        </tr>
                </table>

            {% endblock %}
    {% endembed %}
{% endif %}

src/KGC/ChatBundle/Resources/views/Chat/chat_pricings.html.twig
{% embed '::widgetlayout.html.twig' %}

    {% set widget_options = {
    'titre' : title | default('Consommation générale'),
    'header_class' : 'widget-header-small header-color-blue',
    'refresh' : null,
    'collapse' : true,
    'no_padding' : true,
    } %}

    {% block widget_main %}
    <div class="chat-subscriptions">
        <div class="subscription-container">
            <table class="table valign-middle table-striped table-condensed">
            {% for pricing in pricings %}
                <thead>
                <tr>
                    <th></th>
                    <th>CREDIT</th>
                    <th>MONTANT</th>
                    <th>DATE</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ pricing.offer }}</td>
                    <td>{{ pricing.units }}</td>
                    <td>{{ pricing.price }}</td>
                    <td>{{ pricing.date | date('d/m/Y') }}</td>
                </tr>
                <tr>
                    <td>Restant</td>
                    <td colspan="3" class="chat-subscriptions-left">{{ pricing.left }}</td>
                </tr>
                <tr>
                    <td>Consommation</td>
                    <td colspan="3">{{ pricing.consumed }}</td>
                </tr>
                </tbody>
            {% else %}
                <tr>
                    <td>Aucune consommation</td>
                </tr>
            {% endfor %}
            </table>
        </div>
        {% if actionButtons|default(false) == true %}
        <table class="table valign-middle table-striped table-condensed">
            <tr>
                <td{% if pricings|length > 0 %} colspan="4"{% endif %}>
                    <a class="modal-load btn btn-xs btn-danger" href="{{ path('kgc_chat_formulas_offer', {id: client.id}) }}">{% if chatType|default(0) == 0 %}Offrir du temps{% else %}Offrir des questions{% endif %}</a>
                    {% if client.lastSubscription %}
                    <a class="modal-load btn btn-xs btn-danger" href="{{ path('kgc_chat_formulas_manual_subscription', {id: client.lastSubscription.id}) }}" title="Saisir un paiement lié à l'abonnement actif manuellement">Abonnement manuel</a>
                    {% endif %}
                </td>
            </tr>
        </table>
        {% endif %}
    </div>
    {% endblock %}
{% endembed %}

src/KGC/ChatBundle/Resources/views/Chat/chat_status.html.twig
{% set class = status == 0 ? 'warning' : (status == 1 ? 'info' : (status == 2 ? 'success' : ('danger'))) %}
{% set text = status == 0 ? 'En attente' : (status == 1 ? 'En cours' : (status == 2 ? 'Fermé' : ('Refusé'))) %}

<span class="label label-lg label-{{ class }} arrowed-in arrowed-right tooltip-{{ class }}" title="" data-rel="tooltip" data-original-title="{{ text }}">
   <i class="icon-comments-alt bigger-120"></i>
</span>

src/KGC/ChatBundle/Resources/views/Chat/client_show_messages.html.twig
{% extends not app.request.isXmlHttpRequest() ? '::layout.html.twig' : '::emptylayout.html.twig' %}

{% block body %}
   {% embed '::widgetlayout.html.twig' %}

      {% set widget_options = {
      'titre' : 'Historique de la consultation par chat du '~ room.startDate | date('d/m/Y'),
      'header_class' : 'widget-header-small header-color-blue',
      'refresh' : null,
      'collapse' : false,
      'no_padding' : false,
      } %}

      {% block widget_main %}
         {% for message in room.chatMessages %}
            <div style="border:1px solid #ccc;padding:10px; margin-bottom:10px;">
               <strong>{{ message.chatParticipant.participantName }}</strong><br />
               <small>{{ message.dateCreated | date('d/m/Y H:i') }}</small>
               <br />
               {{ message.content }}
            </div>
         {% endfor %}

      {% endblock %}
   {% endembed %}
{% endblock body %}

src/KGC/ChatBundle/Resources/views/Chat/client_show_single.html.twig
{% extends not app.request.isXmlHttpRequest() ? '::layout.html.twig' : '::emptylayout.html.twig' %}

{% block body %}
    {% embed '::modallayout.html.twig' %}

        {% block modal_title %}Conversation par tchat du {{ room.startDate | date('d/m/Y') }}{% endblock modal_title %}

        {% block modal_body %}
            <div class="row">
                <div class="col-md-6">
                    {% include 'KGCChatBundle:Chat:chat_client.html.twig' with {'client': client, 'website': website} only %}
                </div>
                <div class="col-md-6">
                    <table class="table table-striped table-bordered">
                        <tbody>
                        <tr>
                            <th>
                                <span>Statut</span>
                            </th>
                            <td>
                                {% include 'KGCChatBundle:Chat:chat_status.html.twig' with {'status': room.status} only %}
                            </td>
                        </tr>
                        <tr>
                            <th>
                                <span>Site</span>
                            </th>
                            <td>
                                {{ room.website.libelle }}
                            </td>
                        </tr>
                        <tr>
                            <th>
                                <span>Début du tchat</span>
                            </th>
                            <td>
                                {{ room.startDate ? room.startDate | date('d/m/Y H:i:s'): '-' }}
                            </td>
                        </tr>
                        <tr>
                            <th>
                                <span>Fin du tchat</span>
                            </th>
                            <td>
                                {{ room.endDate ? room.endDate | date('d/m/Y H:i:s') : '-'}}
                            </td>
                        </tr>
                        <tr>
                            <th>
                                <span>Voyant</span>
                            </th>
                            <td>
                                {{ room.psychicParticipant.virtualPsychicName }}
                            </td>
                        </tr>
                        <tr>
                            <th>
                                <span>Consultant</span>
                            </th>
                            <td>
                                {{ room.psychicParticipant.physicalPsychicName }}
                            </td>
                        </tr>
                        <tr>
                            <th>
                                <span>UTM Source</span>
                            </th>
                            <td>
                                {{ room.source }}
                            </td>
                        </tr>
                        </tbody>
                    </table>
                    {% set title = 'Consommation pour le tchat' %}
                    {% include 'KGCChatBundle:Chat:chat_pricings.html.twig' with {'title':title, 'pricings': pricings} only %}
                </div>
            </div>
        {% endblock modal_body %}
    {% endembed %}
{% endblock body %}